apiVersion: apps/v1
kind: Deployment
metadata:
  name: notify-service
spec:
  selector:
    matchLabels:
      app: notify-service
  replicas: 1
  template:
    metadata:
      labels:
        app: notify-service
    spec:
      containers:
        - name: notify-service
          image: iad.ocir.io/cesdev/notify-service/order-management
          imagePullPolicy: Always
          ports:
            - name: notify-service
              containerPort: 8080
              protocol: TCP
      imagePullSecrets:
        - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: notify-service-lb
  labels:
    app: notify-service
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
spec:
  type: LoadBalancer
  ports:
    - port: 8080
  selector:
    app: notify-service