apiVersion: apps/v1
kind: Deployment
metadata:
  name: email-notification-service
spec:
  selector:
    matchLabels:
      app: email-notification-service
  replicas: 2
  template:
    metadata:
      labels:
        app: email-notification-service
    spec:
      containers:
        - name: email-notification-service
          image: iad.ocir.io/cesdev/email-notification-service/order-management
          imagePullPolicy: Always
          ports:
            - name: email-notification-service
              containerPort: 8095
              protocol: TCP
      imagePullSecrets:
        - name: ocirsecret
---
apiVersion: v1
kind: Service
metadata:
  name: email-notification-service-lb
  labels:
    app: email-notification-service
  annotations:
    service.beta.kubernetes.io/oci-load-balancer-shape: "flexible"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-min: "10"
    service.beta.kubernetes.io/oci-load-balancer-shape-flex-max: "100"
spec:
  type: LoadBalancer
  ports:
    - port: 8095
  selector:
    app: email-notification-service